# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: veinsgym.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='veinsgym.proto',
  package='veinsgym.proto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0eveinsgym.proto\x12\x0eveinsgym.proto\"\x9a\x01\n\x07Request\x12\n\n\x02id\x18\x01 \x01(\x04\x12$\n\x04init\x18\x02 \x01(\x0b\x32\x14.veinsgym.proto.InitH\x00\x12,\n\x08shutdown\x18\x03 \x01(\x0b\x32\x18.veinsgym.proto.ShutdownH\x00\x12$\n\x04step\x18\x04 \x01(\x0b\x32\x14.veinsgym.proto.StepH\x00\x42\t\n\x07payload\"\x9b\x01\n\x05Reply\x12\n\n\x02id\x18\x01 \x01(\x04\x12$\n\x04init\x18\x02 \x01(\x0b\x32\x14.veinsgym.proto.InitH\x00\x12,\n\x08shutdown\x18\x03 \x01(\x0b\x32\x18.veinsgym.proto.ShutdownH\x00\x12\'\n\x06\x61\x63tion\x18\x04 \x01(\x0b\x32\x15.veinsgym.proto.SpaceH\x00\x42\t\n\x07payload\"\\\n\x04Init\x12\x19\n\x11\x61\x63tion_space_code\x18\x01 \x01(\t\x12\x1e\n\x16observation_space_code\x18\x02 \x01(\t\x12\x19\n\x11reward_space_code\x18\x03 \x01(\t\"\n\n\x08Shutdown\"Y\n\x04Step\x12*\n\x0bobservation\x18\x01 \x01(\x0b\x32\x15.veinsgym.proto.Space\x12%\n\x06reward\x18\x02 \x01(\x0b\x32\x15.veinsgym.proto.Space\"\x9e\x02\n\x05Space\x12\"\n\x03\x62ox\x18\x01 \x01(\x0b\x32\x13.veinsgym.proto.BoxH\x00\x12$\n\x04\x64ict\x18\x02 \x01(\x0b\x32\x14.veinsgym.proto.DictH\x00\x12,\n\x08\x64iscrete\x18\x03 \x01(\x0b\x32\x18.veinsgym.proto.DiscreteH\x00\x12\x33\n\x0cmulti_binary\x18\x04 \x01(\x0b\x32\x1b.veinsgym.proto.MultiBinaryH\x00\x12\x37\n\x0emulti_discrete\x18\x05 \x01(\x0b\x32\x1d.veinsgym.proto.MultiDiscreteH\x00\x12&\n\x05tuple\x18\x06 \x01(\x0b\x32\x15.veinsgym.proto.TupleH\x00\x42\x07\n\x05value\"\x15\n\x03\x42ox\x12\x0e\n\x06values\x18\x01 \x03(\x01\"l\n\x04\x44ict\x12)\n\x06values\x18\x01 \x03(\x0b\x32\x19.veinsgym.proto.Dict.Item\x1a\x39\n\x04Item\x12\x0b\n\x03key\x18\x01 \x01(\t\x12$\n\x05value\x18\x02 \x01(\x0b\x32\x15.veinsgym.proto.Space\"\x19\n\x08\x44iscrete\x12\r\n\x05value\x18\x01 \x01(\x04\"\x1d\n\x0bMultiBinary\x12\x0e\n\x06values\x18\x01 \x03(\x08\"\x1f\n\rMultiDiscrete\x12\x0e\n\x06values\x18\x01 \x03(\x04\".\n\x05Tuple\x12%\n\x06values\x18\x01 \x03(\x0b\x32\x15.veinsgym.proto.Spaceb\x06proto3'
)




_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='veinsgym.proto.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='veinsgym.proto.Request.id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='init', full_name='veinsgym.proto.Request.init', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='shutdown', full_name='veinsgym.proto.Request.shutdown', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='step', full_name='veinsgym.proto.Request.step', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='payload', full_name='veinsgym.proto.Request.payload',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=35,
  serialized_end=189,
)


_REPLY = _descriptor.Descriptor(
  name='Reply',
  full_name='veinsgym.proto.Reply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='veinsgym.proto.Reply.id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='init', full_name='veinsgym.proto.Reply.init', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='shutdown', full_name='veinsgym.proto.Reply.shutdown', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='action', full_name='veinsgym.proto.Reply.action', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='payload', full_name='veinsgym.proto.Reply.payload',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=192,
  serialized_end=347,
)


_INIT = _descriptor.Descriptor(
  name='Init',
  full_name='veinsgym.proto.Init',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='action_space_code', full_name='veinsgym.proto.Init.action_space_code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='observation_space_code', full_name='veinsgym.proto.Init.observation_space_code', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reward_space_code', full_name='veinsgym.proto.Init.reward_space_code', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=349,
  serialized_end=441,
)


_SHUTDOWN = _descriptor.Descriptor(
  name='Shutdown',
  full_name='veinsgym.proto.Shutdown',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=443,
  serialized_end=453,
)


_STEP = _descriptor.Descriptor(
  name='Step',
  full_name='veinsgym.proto.Step',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='observation', full_name='veinsgym.proto.Step.observation', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reward', full_name='veinsgym.proto.Step.reward', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=455,
  serialized_end=544,
)


_SPACE = _descriptor.Descriptor(
  name='Space',
  full_name='veinsgym.proto.Space',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='box', full_name='veinsgym.proto.Space.box', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dict', full_name='veinsgym.proto.Space.dict', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='discrete', full_name='veinsgym.proto.Space.discrete', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='multi_binary', full_name='veinsgym.proto.Space.multi_binary', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='multi_discrete', full_name='veinsgym.proto.Space.multi_discrete', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tuple', full_name='veinsgym.proto.Space.tuple', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='value', full_name='veinsgym.proto.Space.value',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=547,
  serialized_end=833,
)


_BOX = _descriptor.Descriptor(
  name='Box',
  full_name='veinsgym.proto.Box',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='values', full_name='veinsgym.proto.Box.values', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=835,
  serialized_end=856,
)


_DICT_ITEM = _descriptor.Descriptor(
  name='Item',
  full_name='veinsgym.proto.Dict.Item',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='veinsgym.proto.Dict.Item.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='veinsgym.proto.Dict.Item.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=909,
  serialized_end=966,
)

_DICT = _descriptor.Descriptor(
  name='Dict',
  full_name='veinsgym.proto.Dict',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='values', full_name='veinsgym.proto.Dict.values', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_DICT_ITEM, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=858,
  serialized_end=966,
)


_DISCRETE = _descriptor.Descriptor(
  name='Discrete',
  full_name='veinsgym.proto.Discrete',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='veinsgym.proto.Discrete.value', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=968,
  serialized_end=993,
)


_MULTIBINARY = _descriptor.Descriptor(
  name='MultiBinary',
  full_name='veinsgym.proto.MultiBinary',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='values', full_name='veinsgym.proto.MultiBinary.values', index=0,
      number=1, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=995,
  serialized_end=1024,
)


_MULTIDISCRETE = _descriptor.Descriptor(
  name='MultiDiscrete',
  full_name='veinsgym.proto.MultiDiscrete',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='values', full_name='veinsgym.proto.MultiDiscrete.values', index=0,
      number=1, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=1026,
  serialized_end=1057,
)


_TUPLE = _descriptor.Descriptor(
  name='Tuple',
  full_name='veinsgym.proto.Tuple',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='values', full_name='veinsgym.proto.Tuple.values', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=1059,
  serialized_end=1105,
)

_REQUEST.fields_by_name['init'].message_type = _INIT
_REQUEST.fields_by_name['shutdown'].message_type = _SHUTDOWN
_REQUEST.fields_by_name['step'].message_type = _STEP
_REQUEST.oneofs_by_name['payload'].fields.append(
  _REQUEST.fields_by_name['init'])
_REQUEST.fields_by_name['init'].containing_oneof = _REQUEST.oneofs_by_name['payload']
_REQUEST.oneofs_by_name['payload'].fields.append(
  _REQUEST.fields_by_name['shutdown'])
_REQUEST.fields_by_name['shutdown'].containing_oneof = _REQUEST.oneofs_by_name['payload']
_REQUEST.oneofs_by_name['payload'].fields.append(
  _REQUEST.fields_by_name['step'])
_REQUEST.fields_by_name['step'].containing_oneof = _REQUEST.oneofs_by_name['payload']
_REPLY.fields_by_name['init'].message_type = _INIT
_REPLY.fields_by_name['shutdown'].message_type = _SHUTDOWN
_REPLY.fields_by_name['action'].message_type = _SPACE
_REPLY.oneofs_by_name['payload'].fields.append(
  _REPLY.fields_by_name['init'])
_REPLY.fields_by_name['init'].containing_oneof = _REPLY.oneofs_by_name['payload']
_REPLY.oneofs_by_name['payload'].fields.append(
  _REPLY.fields_by_name['shutdown'])
_REPLY.fields_by_name['shutdown'].containing_oneof = _REPLY.oneofs_by_name['payload']
_REPLY.oneofs_by_name['payload'].fields.append(
  _REPLY.fields_by_name['action'])
_REPLY.fields_by_name['action'].containing_oneof = _REPLY.oneofs_by_name['payload']
_STEP.fields_by_name['observation'].message_type = _SPACE
_STEP.fields_by_name['reward'].message_type = _SPACE
_SPACE.fields_by_name['box'].message_type = _BOX
_SPACE.fields_by_name['dict'].message_type = _DICT
_SPACE.fields_by_name['discrete'].message_type = _DISCRETE
_SPACE.fields_by_name['multi_binary'].message_type = _MULTIBINARY
_SPACE.fields_by_name['multi_discrete'].message_type = _MULTIDISCRETE
_SPACE.fields_by_name['tuple'].message_type = _TUPLE
_SPACE.oneofs_by_name['value'].fields.append(
  _SPACE.fields_by_name['box'])
_SPACE.fields_by_name['box'].containing_oneof = _SPACE.oneofs_by_name['value']
_SPACE.oneofs_by_name['value'].fields.append(
  _SPACE.fields_by_name['dict'])
_SPACE.fields_by_name['dict'].containing_oneof = _SPACE.oneofs_by_name['value']
_SPACE.oneofs_by_name['value'].fields.append(
  _SPACE.fields_by_name['discrete'])
_SPACE.fields_by_name['discrete'].containing_oneof = _SPACE.oneofs_by_name['value']
_SPACE.oneofs_by_name['value'].fields.append(
  _SPACE.fields_by_name['multi_binary'])
_SPACE.fields_by_name['multi_binary'].containing_oneof = _SPACE.oneofs_by_name['value']
_SPACE.oneofs_by_name['value'].fields.append(
  _SPACE.fields_by_name['multi_discrete'])
_SPACE.fields_by_name['multi_discrete'].containing_oneof = _SPACE.oneofs_by_name['value']
_SPACE.oneofs_by_name['value'].fields.append(
  _SPACE.fields_by_name['tuple'])
_SPACE.fields_by_name['tuple'].containing_oneof = _SPACE.oneofs_by_name['value']
_DICT_ITEM.fields_by_name['value'].message_type = _SPACE
_DICT_ITEM.containing_type = _DICT
_DICT.fields_by_name['values'].message_type = _DICT_ITEM
_TUPLE.fields_by_name['values'].message_type = _SPACE
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Reply'] = _REPLY
DESCRIPTOR.message_types_by_name['Init'] = _INIT
DESCRIPTOR.message_types_by_name['Shutdown'] = _SHUTDOWN
DESCRIPTOR.message_types_by_name['Step'] = _STEP
DESCRIPTOR.message_types_by_name['Space'] = _SPACE
DESCRIPTOR.message_types_by_name['Box'] = _BOX
DESCRIPTOR.message_types_by_name['Dict'] = _DICT
DESCRIPTOR.message_types_by_name['Discrete'] = _DISCRETE
DESCRIPTOR.message_types_by_name['MultiBinary'] = _MULTIBINARY
DESCRIPTOR.message_types_by_name['MultiDiscrete'] = _MULTIDISCRETE
DESCRIPTOR.message_types_by_name['Tuple'] = _TUPLE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'veinsgym_pb2'
  # @@protoc_insertion_point(class_scope:veinsgym.proto.Request)
  })
_sym_db.RegisterMessage(Request)

Reply = _reflection.GeneratedProtocolMessageType('Reply', (_message.Message,), {
  'DESCRIPTOR' : _REPLY,
  '__module__' : 'veinsgym_pb2'
  # @@protoc_insertion_point(class_scope:veinsgym.proto.Reply)
  })
_sym_db.RegisterMessage(Reply)

Init = _reflection.GeneratedProtocolMessageType('Init', (_message.Message,), {
  'DESCRIPTOR' : _INIT,
  '__module__' : 'veinsgym_pb2'
  # @@protoc_insertion_point(class_scope:veinsgym.proto.Init)
  })
_sym_db.RegisterMessage(Init)

Shutdown = _reflection.GeneratedProtocolMessageType('Shutdown', (_message.Message,), {
  'DESCRIPTOR' : _SHUTDOWN,
  '__module__' : 'veinsgym_pb2'
  # @@protoc_insertion_point(class_scope:veinsgym.proto.Shutdown)
  })
_sym_db.RegisterMessage(Shutdown)

Step = _reflection.GeneratedProtocolMessageType('Step', (_message.Message,), {
  'DESCRIPTOR' : _STEP,
  '__module__' : 'veinsgym_pb2'
  # @@protoc_insertion_point(class_scope:veinsgym.proto.Step)
  })
_sym_db.RegisterMessage(Step)

Space = _reflection.GeneratedProtocolMessageType('Space', (_message.Message,), {
  'DESCRIPTOR' : _SPACE,
  '__module__' : 'veinsgym_pb2'
  # @@protoc_insertion_point(class_scope:veinsgym.proto.Space)
  })
_sym_db.RegisterMessage(Space)

Box = _reflection.GeneratedProtocolMessageType('Box', (_message.Message,), {
  'DESCRIPTOR' : _BOX,
  '__module__' : 'veinsgym_pb2'
  # @@protoc_insertion_point(class_scope:veinsgym.proto.Box)
  })
_sym_db.RegisterMessage(Box)

Dict = _reflection.GeneratedProtocolMessageType('Dict', (_message.Message,), {

  'Item' : _reflection.GeneratedProtocolMessageType('Item', (_message.Message,), {
    'DESCRIPTOR' : _DICT_ITEM,
    '__module__' : 'veinsgym_pb2'
    # @@protoc_insertion_point(class_scope:veinsgym.proto.Dict.Item)
    })
  ,
  'DESCRIPTOR' : _DICT,
  '__module__' : 'veinsgym_pb2'
  # @@protoc_insertion_point(class_scope:veinsgym.proto.Dict)
  })
_sym_db.RegisterMessage(Dict)
_sym_db.RegisterMessage(Dict.Item)

Discrete = _reflection.GeneratedProtocolMessageType('Discrete', (_message.Message,), {
  'DESCRIPTOR' : _DISCRETE,
  '__module__' : 'veinsgym_pb2'
  # @@protoc_insertion_point(class_scope:veinsgym.proto.Discrete)
  })
_sym_db.RegisterMessage(Discrete)

MultiBinary = _reflection.GeneratedProtocolMessageType('MultiBinary', (_message.Message,), {
  'DESCRIPTOR' : _MULTIBINARY,
  '__module__' : 'veinsgym_pb2'
  # @@protoc_insertion_point(class_scope:veinsgym.proto.MultiBinary)
  })
_sym_db.RegisterMessage(MultiBinary)

MultiDiscrete = _reflection.GeneratedProtocolMessageType('MultiDiscrete', (_message.Message,), {
  'DESCRIPTOR' : _MULTIDISCRETE,
  '__module__' : 'veinsgym_pb2'
  # @@protoc_insertion_point(class_scope:veinsgym.proto.MultiDiscrete)
  })
_sym_db.RegisterMessage(MultiDiscrete)

Tuple = _reflection.GeneratedProtocolMessageType('Tuple', (_message.Message,), {
  'DESCRIPTOR' : _TUPLE,
  '__module__' : 'veinsgym_pb2'
  # @@protoc_insertion_point(class_scope:veinsgym.proto.Tuple)
  })
_sym_db.RegisterMessage(Tuple)


# @@protoc_insertion_point(module_scope)
