"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
    RepeatedScalarFieldContainer as google___protobuf___internal___containers___RepeatedScalarFieldContainer,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Iterable as typing___Iterable,
    Optional as typing___Optional,
    Text as typing___Text,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int


DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

class Request(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    id: builtin___int = ...

    @property
    def init(self) -> type___Init: ...

    @property
    def shutdown(self) -> type___Shutdown: ...

    @property
    def step(self) -> type___Step: ...

    def __init__(self,
        *,
        id : typing___Optional[builtin___int] = None,
        init : typing___Optional[type___Init] = None,
        shutdown : typing___Optional[type___Shutdown] = None,
        step : typing___Optional[type___Step] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"init",b"init",u"payload",b"payload",u"shutdown",b"shutdown",u"step",b"step"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"id",b"id",u"init",b"init",u"payload",b"payload",u"shutdown",b"shutdown",u"step",b"step"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions___Literal[u"payload",b"payload"]) -> typing_extensions___Literal["init","shutdown","step"]: ...
type___Request = Request

class Reply(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    id: builtin___int = ...

    @property
    def init(self) -> type___Init: ...

    @property
    def shutdown(self) -> type___Shutdown: ...

    @property
    def action(self) -> type___Space: ...

    def __init__(self,
        *,
        id : typing___Optional[builtin___int] = None,
        init : typing___Optional[type___Init] = None,
        shutdown : typing___Optional[type___Shutdown] = None,
        action : typing___Optional[type___Space] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"action",b"action",u"init",b"init",u"payload",b"payload",u"shutdown",b"shutdown"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"action",b"action",u"id",b"id",u"init",b"init",u"payload",b"payload",u"shutdown",b"shutdown"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions___Literal[u"payload",b"payload"]) -> typing_extensions___Literal["init","shutdown","action"]: ...
type___Reply = Reply

class Init(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    action_space_code: typing___Text = ...
    observation_space_code: typing___Text = ...
    reward_space_code: typing___Text = ...

    def __init__(self,
        *,
        action_space_code : typing___Optional[typing___Text] = None,
        observation_space_code : typing___Optional[typing___Text] = None,
        reward_space_code : typing___Optional[typing___Text] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"action_space_code",b"action_space_code",u"observation_space_code",b"observation_space_code",u"reward_space_code",b"reward_space_code"]) -> None: ...
type___Init = Init

class Shutdown(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    def __init__(self,
        ) -> None: ...
type___Shutdown = Shutdown

class Step(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    @property
    def observation(self) -> type___Space: ...

    @property
    def reward(self) -> type___Space: ...

    def __init__(self,
        *,
        observation : typing___Optional[type___Space] = None,
        reward : typing___Optional[type___Space] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"observation",b"observation",u"reward",b"reward"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"observation",b"observation",u"reward",b"reward"]) -> None: ...
type___Step = Step

class Space(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    @property
    def box(self) -> type___Box: ...

    @property
    def dict(self) -> type___Dict: ...

    @property
    def discrete(self) -> type___Discrete: ...

    @property
    def multi_binary(self) -> type___MultiBinary: ...

    @property
    def multi_discrete(self) -> type___MultiDiscrete: ...

    @property
    def tuple(self) -> type___Tuple: ...

    def __init__(self,
        *,
        box : typing___Optional[type___Box] = None,
        dict : typing___Optional[type___Dict] = None,
        discrete : typing___Optional[type___Discrete] = None,
        multi_binary : typing___Optional[type___MultiBinary] = None,
        multi_discrete : typing___Optional[type___MultiDiscrete] = None,
        tuple : typing___Optional[type___Tuple] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"box",b"box",u"dict",b"dict",u"discrete",b"discrete",u"multi_binary",b"multi_binary",u"multi_discrete",b"multi_discrete",u"tuple",b"tuple",u"value",b"value"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"box",b"box",u"dict",b"dict",u"discrete",b"discrete",u"multi_binary",b"multi_binary",u"multi_discrete",b"multi_discrete",u"tuple",b"tuple",u"value",b"value"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions___Literal[u"value",b"value"]) -> typing_extensions___Literal["box","dict","discrete","multi_binary","multi_discrete","tuple"]: ...
type___Space = Space

class Box(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    values: google___protobuf___internal___containers___RepeatedScalarFieldContainer[builtin___float] = ...

    def __init__(self,
        *,
        values : typing___Optional[typing___Iterable[builtin___float]] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"values",b"values"]) -> None: ...
type___Box = Box

class Dict(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    class Item(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
        key: typing___Text = ...

        @property
        def value(self) -> type___Space: ...

        def __init__(self,
            *,
            key : typing___Optional[typing___Text] = None,
            value : typing___Optional[type___Space] = None,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions___Literal[u"value",b"value"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"key",b"key",u"value",b"value"]) -> None: ...
    type___Item = Item


    @property
    def values(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___Dict.Item]: ...

    def __init__(self,
        *,
        values : typing___Optional[typing___Iterable[type___Dict.Item]] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"values",b"values"]) -> None: ...
type___Dict = Dict

class Discrete(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    value: builtin___int = ...

    def __init__(self,
        *,
        value : typing___Optional[builtin___int] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"value",b"value"]) -> None: ...
type___Discrete = Discrete

class MultiBinary(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    values: google___protobuf___internal___containers___RepeatedScalarFieldContainer[builtin___bool] = ...

    def __init__(self,
        *,
        values : typing___Optional[typing___Iterable[builtin___bool]] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"values",b"values"]) -> None: ...
type___MultiBinary = MultiBinary

class MultiDiscrete(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    values: google___protobuf___internal___containers___RepeatedScalarFieldContainer[builtin___int] = ...

    def __init__(self,
        *,
        values : typing___Optional[typing___Iterable[builtin___int]] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"values",b"values"]) -> None: ...
type___MultiDiscrete = MultiDiscrete

class Tuple(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    @property
    def values(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___Space]: ...

    def __init__(self,
        *,
        values : typing___Optional[typing___Iterable[type___Space]] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"values",b"values"]) -> None: ...
type___Tuple = Tuple
